#!/usr/bin/env bash

wget https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashrc -O ~/.bashrc
wget https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.aliases -O ~/.aliases
wget https://raw.githubusercontent.com/ianremsen/misc/master/.screenrc -O ~/.screenrc
wget https://raw.githubusercontent.com/ianremsen/misc/master/.nanorc -O ~/.nanorc
