#!/usr/bin/env bash
# The script that pulls my dotfiles from Github

if [ -n "$(command -v wget)" ] && [ -x "$( whereis wget | awk '{print $2;}' )" ] ||
                                  [ -x "$( whereis wget | awk '{print $0;}' )" ]; then
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashrc -O ~/.bashrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.aliases -O ~/.aliases
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/.screenrc -O ~/.screenrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/.nanorc -O ~/.nanorc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/updatedot -O ~/updatedot
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/.bash_profile -O ~/.bash_profile
    if ! [ -f ~/.bashspec ]; then
        wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashspec -O ~/.bashspec
    fi
    if ! [ -d ~/.nanosyntax ]; then
        wget botb.club/~ian/nanosyntax.tar.gz -O ~/.nanosyntax.tar.gz
    fi
elif [ -n "$(command -v curl)" ] && [ -x "$( whereis curl | awk '{print $2;}' )" ] ||
                                    [ -x "$( whereis curl | awk '{print $0;}' )" ]; then
    curl https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashrc > ~/.bashrc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.aliases > ~/.aliases
    curl https://raw.githubusercontent.com/ianremsen/misc/master/.screenrc > ~/.screenrc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/.nanorc > ~/.nanorc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/updatedot > ~/updatedot
    curl https://raw.githubusercontent.com/ianremsen/misc/master/.bash_profile > ~/.bash_profile
    if ! [ -f ~/.bashspec ]; then
        curl https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashspec > ~/.bashspec
    fi
    if ! [ -d ~/.nanosyntax ]; then
        curl botb.club/~ian/nanosyntax.tar.gz > ~/.nanosyntax.tar.gz
    fi
else
    echo "Neither wget nor curl are executable. What the hell are you running this on? A toaster? At least you can play DOOM."
    exit 1
fi

cp ~/.bash_profile ~/.profile

chmod +x updatedot

if [ "$REMOTE" == "0" ] && [ "$CYGWIN" != "1" ]; then
    sudo mv ~/updatedot /usr/local/bin
fi

if [ -f ~/nanosyntax.tar.gz ]; then
    cd; tar zxfv nanosyntax.tar.gz
fi

source ~/.bash_profile
