#!/usr/bin/env bash

WORKFILE=/opt/bashorg/quotes
QUOTENUM=$(sort -R $WORKFILE | head -n 1)

links -dump http://bash.org/?$QUOTENUM | sed -n '/^.*[X].*$/,/^.*Home.*Latest.*$/{/^.*[X].*$/d;/^.*Home.*Latest.*$/d;p}'
