#!/usr/bin/env bash
# JOHN CENA!!! Requires mpg123, amixer, pulseaudio, and
# an mp3 of the John Cena entrance theme.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

amixer -D pulse sset Master 125%
sleep 2
mpg123 ~/Documents/cena.mp3
amixer -D pulse sset Master 75%
