#!/usr/bin/env bash
# JOHN CENA!!! Requires mpg123, amixer, pulseaudio, and
# an mp3 of the John Cena entrance theme.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

VOLUME=125
CHOSEN='cena'
TTW=2

while getopts 't:v:w:' opt; do
	case $opt in
		t)
			CHOSEN=$OPTARG
			;;
		v)
			VOLUME=$OPTARG
			;;
		w)
			TTW=$OPTARG
			;;
	esac
done

FILE='$HOME/.config/cena/$CHOSEN.mp3'

if [ ! -f $FILE ]; then
	echo 'File not found!'
elif (( $VOLUME >= 150 )) || (( $VOLUME <= 0 )); then
	echo 'Invalid volume!'
elif (( $TTW >= 2048 )) || (( $TTW <= 0 )); then
	echo 'Invalid time to wait!'
else
	amixer -D pulse sset Master $VOLUME% > /dev/null &&
	echo '[PLAYING] $CHOSEN.mp3'
	sleep $TTW
	mpg123 $FILE &> /dev/null
	amixer -D pulse sset Master 75% > /dev/null
fi
