#!/usr/bin/env bash
# Little jukebox script. dl requires libav-tools, links, gawk, and youtube-dl to be installed.

RED="\e[1;31m"
CYAN="\e[1;34m"
PURPLE="\e[1;35m"
GREEN="\e[1;32m"
COLX="\e[0m"

WORKFILE=$HOME/.config/goodsongs
LASTFILE=$WORKFILE.last

LINE=$(sort -R $WORKFILE | head -n 1)

NUMSONGS="$GREEN$(wc -l $WORKFILE | tr -d " $WORKFILE")$COLX"
SONGURL=$(echo $LINE | cut -d ';' -f1)
ARTIST=$(echo $LINE | cut -d ';' -f2)
TITLE=$(echo $LINE | cut -d ';' -f3)

LASTURL=$(cat $LASTFILE | cut -d ';' -f1)

NOWPLAYING="$PURPLE$ARTIST - $TITLE$COLX —— $CYAN$SONGURL"
TITLE=$(echo $TITLE | tr -d ' ')
PLAYER=audacious

while getopts "dUnt:a:u:" flag; do
	case "${flag}" in
		n) new=1 ;;
		t) newtitle="${OPTARG}" ;;
		a) newartist="${OPTARG}" ;;
		u) newurl="${OPTARG}" ;;
		U) undo=1 ;;
		d) dl=1 ;;
	esac
done

if [ -n "$new" ] && [ -z $(grep -w "$newartist" $WORKFILE | grep "$newtitle") ] 2>> /dev/null; then
    echo "$newurl;$newartist;$newtitle" >> $WORKFILE 
    echo "$newurl;$newartist;$newtitle" > $LASTFILE
    exit 0
elif [ "$undo" == "1" ]; then
    sed -v "/$LASTURL/d" $WORKFILE > $WORKFILE.temp && mv $WORKFILE.temp $WORKFILE
    exit 0
elif [ "$dl" == "1" ]; then
    youtube-dl -f 140 -o /tmp/$TITLE $SONGURL
    echo "$SONGURL" > $LASTFILE
    echo "$RED[GOODSONG]$COLX Now playing: $NOWPLAYING"
    screen -m -d $PLAYER /tmp/$TITLE
    exit 0
elif [ -n "$new" ]; then
    echo -e "$RED[FAIL]$COLX Put a song that's not there, dummy!"
    exit 1
else
    echo -e "$RED[GOODSONG]$COLX There are $NUMSONGS songs to shuffle from!"
    echo -e "$RED[GOODSONG]$COLX Now playing: $NOWPLAYING"
    x-www-browser $SONGURL 2>> /dev/null
    echo "$SONGURL" > $LASTFILE
    exit 0
fi
