#!/usr/bin/env bash
# Makes a botb.club tarball and transplants it to eu.botb.club

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if   [ "$1" == "create" ] && [ "$HOSTNAME" == "botb.club" ];    then # Creating the tarball
    cd; sudo tar -cvzf publichtml.tar.gz /home/*/public_html/ /var/www/html/ /var/index* /var/default.html # Gross.
    scp publichtml.tar.gz vpn@10.0.0.2:    # Copying it over
    rm  publichtml.tar.gz                  # Deleting the local copy
elif [ "$1" == "unpack" ] && [ "$HOSTNAME" == "zombi" ]; then # So it won't run on botb.club (ech)
    cd ~vpn                                # The user that receives the tarball
    sudo mv  publichtml.tar.gz $HOME; cd   # Moving it home so we can operate on it
    tar zxfv publichtml.tar.gz             # Extracting
    sudo rm  publichtml.tar.gz             # Removing the tarball
    sudo rm -rf /var/www/html/*            # And that's the reason for the hostname check
    sudo mv home/*         /var/www/html   # Stripping the guts out and moving them
    sudo mv var/www/html/* /var/www/html   # to the Apache default directory
                                           # 
    cd /var/www/html                       # Moving to the Apache public directory
    for user in $(ls); do                  # For-loop that adjusts/moves the
        sudo mv $user/public_html/* $user  # public_html dirs and
        sudo mv $user ~$user               # adds tildes as seen on botb.club
        rm ~$user/public_html/ -r          # Also cleans up the now empty dirs
    done                                   #
                                           #
    sudo mv \~index.html index.html        # Cleanup of the slight mess
    sudo mv \~faq.html   faq.html          # the for-loop made
else                                       #
    echo "Specify what you want!"          # In the case that I haven't slept for
fi                                         # a while
