#!/usr/bin/env bash
# Fetches, and prints out >1 bash.org quotes

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

WORKFILE=/etc/quotes
QUOTENUM=$(sort -R $WORKFILE | head -n 1)

if [ "$1" == "update" ]; then
    links -source http://bash.org/?random1 | grep 'Permanent link' | gawk -F ? '{print $2}' | gawk -F \" '{print $1}' >> $WORKFILE
    exit 0
fi

links -dump http://bash.org/?$QUOTENUM | sed -n '/^.*[X].*$/,/^.*Home.*Latest.*$/{/^.*[X].*$/d;/^.*Home.*Latest.*$/d;p}'
