#!/usr/bin/env python
# The maturest piece of software I'm ever likely to write

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import optparse

def main():
  l = optparse.OptionParser()
  l = optparse.OptionParser(description='Generates a beautiful ASCII dong',
                            prog='this',
                            version='this v1.01')
  l.add_option('--length', '-l', default='7',
                            help="customizes the length of the dong")
  options, arguments = l.parse_args()
  try:
    lenPeen = int(options.length)
    if lenPeen <= 400:
      print '8' + ('=' * lenPeen) + 'D'
    elif lenPeen < 0:
      print '8D'
    else:
      print '8=======D'
  except:
      print 'The length has to be a plain whole number, you dong!'

if __name__ == '__main__':
  main()
