#!/usr/bin/env python
import optparse

def main():
  l = optparse.OptionParser()
  l = optparse.OptionParser(description='Generates a beautiful ASCII dong',
                            prog='this',
                            version='this v1.01')
  l.add_option('--length', '-l', default='7',
                            help="customizes the length of the dong")
  options, arguments = l.parse_args()
  try:
    lenPeen = int(options.length)
    if lenPeen <= 400:
      print '8' + ('=' * lenPeen) + 'D'
    elif lenPeen < 0:
      print '8D'
    else:
      print '8=======D'
  except:
      print 'The length has to be a plain whole number, you dong!'

if __name__ == '__main__':
  main()
