#!/usr/bin/env bash

cat ~ian/admin_html/indexstatic.html > /var/www/html/index.html
for user in $(ls /home)
do
    if [ "$(md5sum /home/$user/public_html/index.html | awk '{print $1}')" == "18394b347fbcad6ceacbaf3a1ba8d3f5" ]; then
        echo "<li><a href='/~$user'>$user</a> (default)</li>" >> /var/www/html/index.html
    else
        echo "<li><a href='/~$user'>$user</a></li>" >> /var/www/html/index.html
    fi
done

cat ~ian/admin_html/indexfooter.html >> /var/www/html/index.html

# For updating the botb.club homepage, to be run once a minute
