#!/usr/bin/env bash
# The script that pulls my dotfiles from Github

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -n $(command -v wget) ] && [ -x $( whereis wget | awk '{print $2;}' ) ] ||
                                [ -x $( whereis wget | awk '{print $0;}' ) ]; then
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.bashrc -O ~/.bashrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.aliases -O ~/.aliases
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.screenrc -O ~/.screenrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.nanorc -O ~/.nanorc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/utils/updatedot -O ~/updatedot
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.bash_profile -O ~/.bash_profile
    if ! [ -f ~/.bashspec ]; then
        wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.bashspec -O ~/.bashspec
    fi
    if [ $REMOTE == 0 ] && [ -n $(command -v tmux) ]; then
        wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.tmux.conf.local -O ~/.tmux.conf
    else
        wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.tmux.conf.remote -O ~/.tmux.conf
    fi
elif [ -n $(command -v curl) ] && [ -x $( whereis curl | awk '{print $2;}' ) ] ||
                                  [ -x $( whereis curl | awk '{print $0;}' ) ]; then
    curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.bashrc > ~/.bashrc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.aliases > ~/.aliases
    curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.screenrc > ~/.screenrc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.nanorc > ~/.nanorc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/utils/updatedot > ~/updatedot
    curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.bash_profile > ~/.bash_profile
    if ! [ -f ~/.bashspec ] && ! [ -d /usr/share/nano ]; then
        curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.bashspec > ~/.bashspec
    fi
    if [ $REMOTE == 0 ] && [ -n $(command -v tmux) ]; then
        curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.tmux.conf.local > ~/.tmux.conf
    else
        curl https://raw.githubusercontent.com/ianremsen/misc/master/dotfiles/.tmux.conf.remote > ~/.tmux.conf
    fi
else
    echo 'Neither wget nor curl are executable.'
    exit 1
fi

cp ~/.bash_profile ~/.profile

chmod +x updatedot

if [ $REMOTE == 0 ]; then
	sudo mv ~/updatedot /usr/local/bin
fi

source ~/.bash_profile
