#!/usr/bin/env bash
# The script that pulls my dotfiles from Github

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -n "$(command -v wget)" ] && [ -x "$( whereis wget | awk '{print $2;}' )" ] ||
                                  [ -x "$( whereis wget | awk '{print $0;}' )" ]; then
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashrc -O ~/.bashrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.aliases -O ~/.aliases
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/.screenrc -O ~/.screenrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/.nanorc -O ~/.nanorc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/updatedot -O ~/updatedot
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/.bash_profile -O ~/.bash_profile
    if ! [ -f ~/.bashspec ]; then
        wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashspec -O ~/.bashspec
    fi
elif [ -n "$(command -v curl)" ] && [ -x "$( whereis curl | awk '{print $2;}' )" ] ||
                                    [ -x "$( whereis curl | awk '{print $0;}' )" ]; then
    curl https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashrc > ~/.bashrc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.aliases > ~/.aliases
    curl https://raw.githubusercontent.com/ianremsen/misc/master/.screenrc > ~/.screenrc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/.nanorc > ~/.nanorc
    curl https://raw.githubusercontent.com/ianremsen/misc/master/updatedot > ~/updatedot
    curl https://raw.githubusercontent.com/ianremsen/misc/master/.bash_profile > ~/.bash_profile
    if ! [ -f ~/.bashspec ] && ! [ -d /usr/share/nano ]; then
        curl https://raw.githubusercontent.com/ianremsen/misc/master/bashrc/.bashspec > ~/.bashspec
    fi
else
    echo "Neither wget nor curl are executable. What the hell are you running this on? A toaster? At least you can play DOOM."
    exit 1
fi

cp ~/.bash_profile ~/.profile

chmod +x ~/updatedot

if [ "$REMOTE" == "0" ] && [ "$CYGWIN" != "1" ]; then
    sudo mv ~/updatedot /usr/local/bin
fi

source ~/.bash_profile
