#!/usr/bin/env bash
# For updating the botb.club homepage, to be run once a minute

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

MD5="18394b347fbcad6ceacbaf3a1ba8d3f5"

cat /var/indexstatic.html > /var/www/html/index.html
for user in $(ls /home); do
    INDEX="/home/$user/public_html/index.html"
    if [ -f $INDEX ] && [ "$(md5sum $INDEX | awk '{print $1}')" != $MD5 ]; then
        echo "<li><a href='/~$user'>$user</a></li>" >> /var/www/html/index.html
    fi
done

cat /var/indexfooter.html >> /var/www/html/index.html
