.TH THIS 1
.SH NAME
this \- prints customizable BotB injokes
.SH SYNOPSIS
.B this
[\fB\-l\fR \fILENGTH\fR]
.SH DESCRIPTION
.B this
prints customizable injokes from http://battleofthebits.org
.SH OPTIONS
.TP
.BR \-l ", " \-\-length =\fILENGTH\fR
Set the length of the printed dong. Negative numbers print the dong "backwards".
Default is 7.

