#!/usr/bin/env bash

WORKFILE=$HOME/.goodsongs
LASTURL=$(cat $HOME/.goodsongs.last)

if [ "$1" == "undo" ]; then
    grep -v "$LASTURL" $WORKFILE > $WORKFILE.temp && mv $WORKFILE.temp $WORKFILE
    exit 0
fi

if [ -n "$1" ] && ! [ -n "$(grep -w $1 $WORKFILE)" ]; then
    echo "$1" >> $WORKFILE
    echo "$1" > $HOME/.goodsongs.last
else
    echo "Put a URL that's not there, dummy!"
fi
